# RabbitMQ server configuration used for docker/dev-compose
# Instruct the management plugin to load definitions from the mounted file
management.load_definitions = /etc/rabbitmq/definitions.json

# Allow guest user remote access in dev (if needed). Uncomment to enable:
# loopback_users.guest = false
