import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import SwaggerParser from '@apidevtools/swagger-parser';
import Ajv from 'ajv';
import addFormats from 'ajv-formats';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const workspaceRoot = path.resolve(__dirname, '..');
const openApiPath = path.join(workspaceRoot, 'openapi', 'governance.yaml');

const fixtureSchemaPairs = [
  ['schemas/fixtures/ingest-request.json', 'IngestRequest'],
  ['schemas/fixtures/job-submit-request.json', 'JobSubmitRequest'],
  ['schemas/fixtures/job-status-response.json', 'JobStatusResponse'],
  ['schemas/fixtures/dataset-request-with-manifest.json', 'DatasetRequest'],
  ['schemas/fixtures/dataset-response-with-manifest.json', 'DatasetResponse'],
  ['schemas/fixtures/trident-scheduling-block.json', 'SchedulingBlock'],
  ['schemas/fixtures/trident-execution-block.json', 'ExecutionBlock'],
  ['schemas/fixtures/trident-subarray-configuration.json', 'SubarrayConfiguration'],
  ['schemas/fixtures/trident-spectral-configuration.json', 'SpectralConfiguration'],
  ['schemas/fixtures/trident-fsp-allocation-plan.json', 'FspAllocationPlan'],
];

// Use parse so we can merge component fragments before dereferencing
const openapi = await SwaggerParser.parse(openApiPath);
// attempt to load trident fragment and merge component schemas so fixtures can be validated
const tridentPath = path.join(workspaceRoot, 'openapi', 'trident-schemas.yaml');
try {
  const trident = await SwaggerParser.parse(tridentPath);
  if (trident && trident.components && trident.components.schemas) {
    openapi.components = openapi.components || {};
    openapi.components.schemas = openapi.components.schemas || {};
    const tridentDir = path.dirname(tridentPath);
    for (const [name, def] of Object.entries(trident.components.schemas)) {
      if (def && def.$ref && typeof def.$ref === 'string') {
        // resolve ref relative to the trident fragment and inline the JSON schema
        const refFile = def.$ref.split('#')[0];
        const abs = path.resolve(tridentDir, refFile);
        if (fs.existsSync(abs)) {
          try {
            openapi.components.schemas[name] = JSON.parse(fs.readFileSync(abs, 'utf8'));
            continue;
          } catch (e) {
            // fall through to copy ref node if parsing fails
          }
        }
        // fallback: try packaged resources path where schemas may be located
        const packagedCandidate = path.resolve(workspaceRoot, 'apps', 'java-governance', 'src', 'main', 'resources', 'schemas', path.basename(refFile));
        if (fs.existsSync(packagedCandidate)) {
          try {
            openapi.components.schemas[name] = JSON.parse(fs.readFileSync(packagedCandidate, 'utf8'));
            continue;
          } catch (e) {
            // fall through
          }
        }
      }
      openapi.components.schemas[name] = def;
    }
  }
} catch (e) {
  // ignore missing trident fragment — validation will fail later if schemas are required
}
// If root openapi is missing common components (e.g. HealthResponse), try merging
// the packaged static OpenAPI generated by the Java app so refs resolve.
try {
  const packagedPath = path.join(workspaceRoot, 'apps', 'java-governance', 'src', 'main', 'resources', 'static', 'openapi', 'governance.yaml');
  const packaged = await SwaggerParser.parse(packagedPath);
  if (packaged && packaged.components && packaged.components.schemas) {
    openapi.components = openapi.components || {};
    openapi.components.schemas = openapi.components.schemas || {};
    const pkgDir = path.dirname(packagedPath);
    for (const [name, def] of Object.entries(packaged.components.schemas)) {
      if (def && def.$ref && typeof def.$ref === 'string') {
        const refFile = def.$ref.split('#')[0];
        const abs = path.resolve(pkgDir, refFile);
        if (fs.existsSync(abs)) {
          try {
            openapi.components.schemas[name] = JSON.parse(fs.readFileSync(abs, 'utf8'));
            continue;
          } catch (e) {
            // fall through
          }
        }
      }
      openapi.components.schemas[name] = def;
    }
  }
} catch (e) {
  // ignore — packaged static openapi may not exist in all workspaces
}
// Build a clean, flat schemas map — deep-copy each schema using JSON round-trip so
// we always work with pure data objects (no leftover circular JS refs from any parser).
// Strip $schema/$id so AJV doesn't attempt remote meta-schema resolution.
const allSchemas = (openapi.components && openapi.components.schemas) || {};
const cleanSchemas = {};
for (const [name, s] of Object.entries(allSchemas)) {
  if (!s || typeof s !== 'object') continue;
  try {
    const copy = JSON.parse(JSON.stringify(s));
    delete copy.$schema;
    delete copy.$id;
    cleanSchemas[name] = copy;
  } catch (_) { /* skip schemas that couldn't be serialised */ }
}

if (Object.keys(cleanSchemas).length === 0) {
  throw new Error('OpenAPI components.schemas is missing or empty.');
}

// Validate each fixture against its schema.
// We compile a fresh wrapper per schema so AJV resolves internal $ref strings of the
// form "#/components/schemas/X" by navigating the wrapper object itself — no external
// URI resolution, no AJV schema-registry cross-contamination between fixtures.
for (const [fixtureRelPath, schemaName] of fixtureSchemaPairs) {
  if (!cleanSchemas[schemaName]) {
    throw new Error(`Schema "${schemaName}" not found in OpenAPI components.`);
  }

  const fixturePath = path.join(workspaceRoot, fixtureRelPath);
  const fixture = JSON.parse(fs.readFileSync(fixturePath, 'utf8'));

  // Each fixture gets its own isolated AJV instance to avoid any compiled-schema
  // cache sharing that could carry circular-ref artefacts between schemas.
  const ajv = new Ajv({ allErrors: true, strict: false });
  addFormats(ajv);

  // The wrapper embeds ALL component schemas so that any intra-document $ref of the
  // form "#/components/schemas/X" navigates to wrapper.components.schemas.X directly.
  const wrapper = {
    $ref: `#/components/schemas/${schemaName}`,
    components: { schemas: cleanSchemas },
  };
  const validate = ajv.compile(wrapper);

  const valid = validate(fixture);
  if (!valid) {
    const details = JSON.stringify(validate.errors, null, 2);
    throw new Error(`Fixture ${fixtureRelPath} failed schema ${schemaName} validation:\n${details}`);
  }
}

console.log(`OpenAPI validation passed: ${openApiPath}`);
console.log(`Validated fixtures: ${fixtureSchemaPairs.length}`);
