import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import SwaggerParser from '@apidevtools/swagger-parser';
import Ajv from 'ajv';
import addFormats from 'ajv-formats';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const workspaceRoot = path.resolve(__dirname, '..');
const openApiPath = path.join(workspaceRoot, 'openapi', 'governance.yaml');

const fixtureSchemaPairs = [
  ['schemas/fixtures/ingest-request.json', 'IngestRequest'],
  ['schemas/fixtures/job-submit-request.json', 'JobSubmitRequest'],
  ['schemas/fixtures/job-status-response.json', 'JobStatusResponse'],
  ['schemas/fixtures/dataset-request-with-manifest.json', 'DatasetRequest'],
  ['schemas/fixtures/dataset-response-with-manifest.json', 'DatasetResponse'],
  ['schemas/fixtures/trident-scheduling-block.json', 'SchedulingBlock'],
  ['schemas/fixtures/trident-execution-block.json', 'ExecutionBlock'],
  ['schemas/fixtures/trident-subarray-configuration.json', 'SubarrayConfiguration'],
  ['schemas/fixtures/trident-spectral-configuration.json', 'SpectralConfiguration'],
  ['schemas/fixtures/trident-fsp-allocation-plan.json', 'FspAllocationPlan'],
];

// Use parse so we can merge component fragments before dereferencing
const openapi = await SwaggerParser.parse(openApiPath);
// attempt to load trident fragment and merge component schemas so fixtures can be validated
const tridentPath = path.join(workspaceRoot, 'openapi', 'trident-schemas.yaml');
try {
  const trident = await SwaggerParser.parse(tridentPath);
  if (trident && trident.components && trident.components.schemas) {
    openapi.components = openapi.components || {};
    openapi.components.schemas = openapi.components.schemas || {};
    const tridentDir = path.dirname(tridentPath);
    for (const [name, def] of Object.entries(trident.components.schemas)) {
      if (def && def.$ref && typeof def.$ref === 'string') {
        // resolve ref relative to the trident fragment and inline the JSON schema
        const refFile = def.$ref.split('#')[0];
        const abs = path.resolve(tridentDir, refFile);
        if (fs.existsSync(abs)) {
          try {
            openapi.components.schemas[name] = JSON.parse(fs.readFileSync(abs, 'utf8'));
            continue;
          } catch (e) {
            // fall through to copy ref node if parsing fails
          }
        }
        // fallback: try packaged resources path where schemas may be located
        const packagedCandidate = path.resolve(workspaceRoot, 'apps', 'java-governance', 'src', 'main', 'resources', 'schemas', path.basename(refFile));
        if (fs.existsSync(packagedCandidate)) {
          try {
            openapi.components.schemas[name] = JSON.parse(fs.readFileSync(packagedCandidate, 'utf8'));
            continue;
          } catch (e) {
            // fall through
          }
        }
      }
      openapi.components.schemas[name] = def;
    }
  }
} catch (e) {
  // ignore missing trident fragment — validation will fail later if schemas are required
}
// If root openapi is missing common components (e.g. HealthResponse), try merging
// the packaged static OpenAPI generated by the Java app so refs resolve.
try {
  const packagedPath = path.join(workspaceRoot, 'apps', 'java-governance', 'src', 'main', 'resources', 'static', 'openapi', 'governance.yaml');
  const packaged = await SwaggerParser.parse(packagedPath);
  if (packaged && packaged.components && packaged.components.schemas) {
    openapi.components = openapi.components || {};
    openapi.components.schemas = openapi.components.schemas || {};
    const pkgDir = path.dirname(packagedPath);
    for (const [name, def] of Object.entries(packaged.components.schemas)) {
      if (def && def.$ref && typeof def.$ref === 'string') {
        const refFile = def.$ref.split('#')[0];
        const abs = path.resolve(pkgDir, refFile);
        if (fs.existsSync(abs)) {
          try {
            openapi.components.schemas[name] = JSON.parse(fs.readFileSync(abs, 'utf8'));
            continue;
          } catch (e) {
            // fall through
          }
        }
      }
      openapi.components.schemas[name] = def;
    }
  }
} catch (e) {
  // ignore — packaged static openapi may not exist in all workspaces
}
// Attempt to bundle (flatten external $refs) the merged document so component schemas are self-contained.
let mergedOpenapi = openapi;
try {
  // bundle is more forgiving for external refs and will inline referenced files into the document
  mergedOpenapi = await SwaggerParser.bundle(openapi);
} catch (e) {
  try {
    mergedOpenapi = await SwaggerParser.dereference(openapi);
  } catch (err) {
    // If both bundling and dereference fail, keep parsed+merged document and attempt best-effort validation.
  }
}
const ajv = new Ajv({ allErrors: true, strict: false });
addFormats(ajv);

if (!mergedOpenapi.components || !mergedOpenapi.components.schemas) {
  throw new Error('OpenAPI components.schemas is missing.');
}

// Deep-copy every component schema to break any circular JS references left by the
// parser/bundler, strip $schema/$id meta (prevents remote meta-schema fetch attempts),
// and rewrite intra-document OpenAPI $refs (#/components/schemas/X) to stable URNs
// (urn:cs:X) that AJV can resolve via its own schema registry.
const cleanDefs = {};
for (const [name, s] of Object.entries(mergedOpenapi.components.schemas)) {
  try {
    const rewritten = JSON.parse(
      JSON.stringify(s).replace(/"#\/components\/schemas\/([^"]+)"/g, '"urn:cs:$1"')
    );
    delete rewritten.$schema;
    delete rewritten.$id;
    cleanDefs[name] = rewritten;
  } catch (_) { /* skip unserializable schemas */ }
}

// Register all component schemas in AJV keyed by their URN so that cross-schema
// $refs (rewritten above to urn:cs:X) resolve without any JSON pointer traversal.
for (const [name, schema] of Object.entries(cleanDefs)) {
  try {
    ajv.addSchema(schema, `urn:cs:${name}`);
  } catch (_) { /* ignore duplicate-key errors on re-runs */ }
}

for (const [fixtureRelPath, schemaName] of fixtureSchemaPairs) {
  const schema = cleanDefs[schemaName];
  if (!schema) {
    throw new Error(`Schema "${schemaName}" not found in OpenAPI document.`);
  }

  const fixturePath = path.join(workspaceRoot, fixtureRelPath);
  const fixture = JSON.parse(fs.readFileSync(fixturePath, 'utf8'));

  // getSchema returns the lazily-compiled validate function for the pre-registered URN.
  const validate = ajv.getSchema(`urn:cs:${schemaName}`) ?? ajv.compile(schema);

  const valid = validate(fixture);
  if (!valid) {
    const details = JSON.stringify(validate.errors, null, 2);
    throw new Error(`Fixture ${fixtureRelPath} failed schema ${schemaName} validation:\n${details}`);
  }
}

console.log(`OpenAPI validation passed: ${openApiPath}`);
console.log(`Validated fixtures: ${fixtureSchemaPairs.length}`);
